ALTER TABLE "TNT_FLASH_PARAMS" ALTER COLUMN "in_use" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "TNT_PARAMS" ALTER COLUMN "in_use" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "TNT_STROBE_PARAMS" ALTER COLUMN "in_use" SET DEFAULT false;