ALTER TABLE "TNT_FLASH_PARAMS" ADD COLUMN "id" serial PRIMARY KEY NOT NULL;--> statement-breakpoint
ALTER TABLE "TNT_PARAMS" ADD COLUMN "id" serial PRIMARY KEY NOT NULL;--> statement-breakpoint
ALTER TABLE "TNT_STROBE_PARAMS" ADD COLUMN "id" serial PRIMARY KEY NOT NULL;