ALTER TABLE "TNT_FLASH_DATA" RENAME TO "TNT_GLOW_DATA";--> statement-breakpoint
ALTER TABLE "TNT_FLASH_INSTRUCTIONS" RENAME TO "TNT_GLOW_INSTRUCTIONS";--> statement-breakpoint
ALTER TABLE "TNT_FLASH_PARAMS" RENAME TO "TNT_GLOW_PARAMS";